apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: ui-trade-manager
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: trades
      operation: Write
    - resource:
        type: topic
        name: trades
      operation: Describe
    - resource:
        type: topic
        name: trades
      operation: Read
    - resource:
        type: group
        name: ui-trade-manager
        patternType: prefix
      operation: Read
---

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: trades
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 107374182
    retention.ms: 86400000
    segment.bytes: 107374182
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ui-trade-manager
  name: ui-trade-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-trade-manager
    spec:
      containers:
      - name: ui-trade-manager
        image: quay.io/scholzj/rh-developer-meetup-brno-2019:ui-trade-manager
        env:
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: ui-trade-manager
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: ui-trade-manager
              key: user.key
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: TOPIC
          value: trades
        - name: GROUP_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---

apiVersion: v1
kind: Service
metadata:
  name: ui-trade-manager
  labels:
    app: ui-trade-manager
spec:
  type: ClusterIP
  ports:
   - name: http
     port: 8080
  selector:
    app: ui-trade-manager
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ui-trade-manager
  labels:
    app: ui-trade-manager
spec:
  to:
    kind: Service
    name: ui-trade-manager
