###########
# Prices Topic
###########

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: prices
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 107374182
    retention.ms: 86400000
    segment.bytes: 107374182
---

###########
# Kafka Connect User
###########

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: my-connect-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    # Connector needs to write to prices topic
    - resource:
        type: topic
        name: prices
      operation: Write
    - resource:
        type: topic
        name: prices
      operation: Describe
    # Kafka Connects internal topics
    - resource:
        type: group
        name: connect-cluster
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Create
---

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  labels:
    app: my-connect-cluster
spec:
  image: quay.io/scholzj/rh-developer-meetup-brno-2019:price-feed-connector
  version: 2.1.1
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 250m
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
    - secretName: my-cluster-cluster-ca-cert
      certificate: ca.crt
  metrics:
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "kafka_connect_connect_worker_metrics_$1"
    - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "kafka_connect_connect_metrics_$1_$2"
  authentication:
    type: tls
    certificateAndKey:
      secretName: my-connect-cluster
      certificate: user.crt
      key: user.key
  jvmOptions:
    gcLoggingEnabled: false
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: my-connect-cluster
  labels:
    app: my-connect-cluster
spec:
  port:
    targetPort: rest-api
  to:
    kind: Service
    name: my-connect-cluster-connect-api
---

###########
# UI Price Viewer
###########

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: ui-price-viewer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: prices
      operation: Read
    - resource:
        type: topic
        name: prices
      operation: Describe
    - resource:
        type: group
        name: ui-price-viewer
        patternType: prefix
      operation: Read
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ui-price-viewer
  name: ui-price-viewer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-price-viewer
    spec:
      containers:
      - name: ui-price-viewer
        image: quay.io/scholzj/rh-developer-meetup-brno-2019:ui-price-viewer
        env:
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: ui-price-viewer
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: ui-price-viewer
              key: user.key
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: TOPIC
          value: prices
        - name: GROUP_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---

apiVersion: v1
kind: Service
metadata:
  name: ui-price-viewer
  labels:
    app: ui-price-viewer
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
  selector:
    app: ui-price-viewer
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ui-price-viewer
  labels:
    app: ui-price-viewer
spec:
  to:
    kind: Service
    name: ui-price-viewer